=== mateomate1/eclipse-workspace/curso2425_UD2_XmlDOM_XPath/alumnos3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xsd:element name="alumnos">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="alumno" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="expediente" type="xsd:string"/>
              <xsd:element name="nombre" type="xsd:string"/>
              <xsd:element name="edad" type="xsd:integer"/>
            </xsd:sequence>
            <xsd:attribute name="curso" type="xsd:string" use="required"/>
            <xsd:attribute name="IES" type="xsd:string" use="optional"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mateomate1/eclipse-workspace/curso2425_UD2_XmlDOM_XPath/alumnos3.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumnos3.xsd">
	<alumno curso="23-24">
		<expediente>11111</expediente>
		<nombre>carlitos</nombre>
		<edad>21</edad>
	</alumno>
	<alumno curso="24-25">
		<expediente>22222</expediente>
		<nombre>menganito</nombre>
		<edad>28</edad>
	</alumno>
	<alumno curso="24-25" IES="Ciudad Escolar">
		<expediente>33333</expediente>
		<nombre>fermin</nombre>
		<edad>24</edad>
	</alumno>
	<alumno curso="24-25">
		<expediente>44444</expediente>
		<nombre>julito</nombre>
		<edad>23</edad>
	</alumno>
</alumnos>
